"""
工具模块初始化
"""

from .exceptions import (
    WatermarkRemoverError,
    ConfigError,
    ImageProcessingError,
    VideoProcessingError,
    FileOperationError,
    ValidationError,
    CacheError,
    TaskError,
)

from .config_loader import ConfigLoader, get_config
from .logger import Logger, get_logger, debug, info, warning, error, critical
from .file_utils import (
    ensure_dir,
    get_file_extension,
    get_filename_without_ext,
    generate_output_path,
    list_files,
    copy_file,
    move_file,
    delete_file,
    clean_directory,
    get_file_size,
    format_file_size,
    video_capture,
    video_writer,
)
from .image_utils import (
    load_image,
    save_image,
    get_image_size,
    resize_image,
    create_mask,
    dilate_mask,
    convert_to_rgba,
    convert_to_bgr,
    get_image_info,
    validate_image,
)
from .validators import (
    validate_file_exists,
    validate_directory_exists,
    validate_image_file,
    validate_video_file,
    validate_roi,
    validate_quality,
    validate_inpainting_radius,
    validate_algorithm,
    validate_output_path,
    get_supported_image_formats,
    get_supported_video_formats,
    is_supported_image_format,
    is_supported_video_format,
    is_ai_algorithm,
    AI_ALGORITHM_KEYWORDS,
)

__all__ = [
    # Exceptions
    'WatermarkRemoverError',
    'ConfigError',
    'ImageProcessingError',
    'VideoProcessingError',
    'FileOperationError',
    'ValidationError',
    'CacheError',
    'TaskError',
    # Config
    'ConfigLoader',
    'get_config',
    # Logger
    'Logger',
    'get_logger',
    'debug',
    'info',
    'warning',
    'error',
    'critical',
    # File utils
    'ensure_dir',
    'get_file_extension',
    'get_filename_without_ext',
    'generate_output_path',
    'list_files',
    'copy_file',
    'move_file',
    'delete_file',
    'clean_directory',
    'get_file_size',
    'format_file_size',
    'video_capture',
    'video_writer',
    # Image utils
    'load_image',
    'save_image',
    'get_image_size',
    'resize_image',
    'create_mask',
    'dilate_mask',
    'convert_to_rgba',
    'convert_to_bgr',
    'get_image_info',
    'validate_image',
    # Validators
    'validate_file_exists',
    'validate_directory_exists',
    'validate_image_file',
    'validate_video_file',
    'validate_roi',
    'validate_quality',
    'validate_inpainting_radius',
    'validate_algorithm',
    'validate_output_path',
    'get_supported_image_formats',
    'get_supported_video_formats',
    'is_supported_image_format',
    'is_supported_video_format',
    'is_ai_algorithm',
    'AI_ALGORITHM_KEYWORDS',
]
